version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www/html
      - ./laravel/storage:/var/www/html/storage
    environment:
      - APP_NAME=Bakery Management System API
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:8000
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=bakery_db
      - DB_USERNAME=bakery_user
      - DB_PASSWORD=bakery_password
      - SANCTUM_STATEFUL_DOMAINS=localhost:3000,127.0.0.1:3000
    depends_on:
      - db
    networks:
      - bakery-network

  # MySQL Database
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: bakery_db
      MYSQL_USER: bakery_user
      MYSQL_PASSWORD: bakery_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - bakery-network

  # phpMyAdmin (Optional - for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: bakery_user
      PMA_PASSWORD: bakery_password
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - bakery-network

volumes:
  mysql_data:

networks:
  bakery-network:
    driver: bridge
