<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeder.
     */
    public function run(): void
    {
        $products = [
            // ARTISAN BREADS Category (Category 1)
            [
                'owner_id' => 2,
                'name' => 'Sourdough Bread Loaf',
                'description' => 'Traditional sourdough with a crispy crust and tangy flavor. Made with our 100-year-old starter.',
                'price' => 8.50,
                'discount_price' => null,
                'category' => 'Artisan Breads',
                'category_id' => 1,
                'stock_quantity' => 20,
                'sku' => 'BREAD-SD-001',
                'weight' => 0.75,
                'dimensions' => '30x15x12cm',
                'ingredients' => json_encode(['flour', 'water', 'salt', 'sourdough starter']),
                'allergens' => json_encode(['gluten']),
                'status' => 'active',
                'rating' => 4.80,
                'rating_count' => 25,
                'is_featured' => true,
                'meta_title' => 'Artisan Sourdough Bread',
                'meta_description' => 'Handcrafted sourdough bread baked fresh daily',
                'image_path' => null,
                'images' => json_encode([]),
            ],
            [
                'owner_id' => 2,
                'name' => 'Multigrain Seeded Bread',
                'description' => 'Healthy multigrain bread topped with sunflower, pumpkin, and sesame seeds. Perfect for health-conscious customers.',
                'price' => 7.50,
                'discount_price' => 6.99,
                'category' => 'Artisan Breads',
                'category_id' => 1,
                'stock_quantity' => 25,
                'sku' => 'BREAD-MG-001',
                'weight' => 0.70,
                'dimensions' => '28x14x12cm',
                'ingredients' => json_encode(['whole wheat flour', 'oats', 'seeds', 'honey', 'yeast']),
                'allergens' => json_encode(['gluten', 'sesame']),
                'status' => 'active',
                'rating' => 4.65,
                'rating_count' => 18,
                'is_featured' => false,
                'meta_title' => 'Healthy Multigrain Bread',
                'meta_description' => 'Nutritious seeded bread from local bakery',
                'image_path' => null,
                'images' => json_encode([]),
            ],
            [
                'owner_id' => 3,
                'name' => 'French Baguette',
                'description' => 'Authentic French baguette with a golden crust and airy interior. Perfect for sandwiches or with cheese.',
                'price' => 3.25,
                'discount_price' => null,
                'category' => 'Artisan Breads',
                'category_id' => 1,
                'stock_quantity' => 30,
                'sku' => 'BREAD-BAG-001',
                'weight' => 0.25,
                'dimensions' => '60x8x8cm',
                'ingredients' => json_encode(['flour', 'water', 'salt', 'yeast']),
                'allergens' => json_encode(['gluten']),
                'status' => 'active',
                'rating' => 4.70,
                'rating_count' => 32,
                'is_featured' => true,
                'meta_title' => 'Classic French Baguette',
                'meta_description' => 'Traditional French baguette baked fresh',
                'image_path' => null,
                'images' => json_encode([]),
            ],

            // CAKES & CELEBRATION Category (Category 2)
            [
                'owner_id' => 3,
                'name' => 'Custom Birthday Cake (8-inch)',
                'description' => 'Personalized birthday cake with custom message and design. Choose your favorite flavor and frosting!',
                'price' => 45.00,
                'discount_price' => null,
                'category' => 'Cakes & Celebration',
                'category_id' => 2,
                'stock_quantity' => 0,
                'sku' => 'CAKE-CUST-001',
                'weight' => 1.50,
                'dimensions' => '20x20x12cm',
                'ingredients' => json_encode(['flour', 'sugar', 'eggs', 'butter', 'custom toppings']),
                'allergens' => json_encode(['gluten', 'dairy', 'eggs']),
                'status' => 'active',
                'rating' => 4.95,
                'rating_count' => 87,
                'is_featured' => true,
                'meta_title' => 'Custom Birthday Cake',
                'meta_description' => 'Personalized birthday cakes made to order',
                'image_path' => null,
                'images' => json_encode([]),
            ],
            [
                'owner_id' => 3,
                'name' => 'Red Velvet Cake',
                'description' => 'Our signature red velvet cake with cream cheese frosting. A southern classic with a modern twist.',
                'price' => 35.00,
                'discount_price' => null,
                'category' => 'Cakes & Celebration',
                'category_id' => 2,
                'stock_quantity' => 8,
                'sku' => 'CAKE-RV-001',
                'weight' => 1.20,
                'dimensions' => '20x20x10cm',
                'ingredients' => json_encode(['flour', 'sugar', 'eggs', 'buttermilk', 'cocoa', 'cream cheese']),
                'allergens' => json_encode(['gluten', 'dairy', 'eggs']),
                'status' => 'active',
                'rating' => 4.88,
                'rating_count' => 67,
                'is_featured' => true,
                'meta_title' => 'Classic Red Velvet Cake',
                'meta_description' => 'Delicious red velvet cake with cream cheese frosting',
                'image_path' => null,
                'images' => json_encode([]),
            ],
            [
                'owner_id' => 2,
                'name' => 'Wedding Cake (3-Tier)',
                'description' => 'Elegant 3-tier wedding cake customizable for your special day. Consultation required before order.',
                'price' => 250.00,
                'discount_price' => null,
                'category' => 'Cakes & Celebration',
                'category_id' => 2,
                'stock_quantity' => 0,
                'sku' => 'CAKE-WED-001',
                'weight' => 5.00,
                'dimensions' => '45x45x40cm',
                'ingredients' => json_encode(['flour', 'sugar', 'eggs', 'butter', 'fondant', 'buttercream']),
                'allergens' => json_encode(['gluten', 'dairy', 'eggs']),
                'status' => 'active',
                'rating' => 5.00,
                'rating_count' => 23,
                'is_featured' => true,
                'meta_title' => 'Custom Wedding Cake',
                'meta_description' => 'Elegant wedding cakes for your special day',
                'image_path' => null,
                'images' => json_encode([]),
            ],
            [
                'owner_id' => 3,
                'name' => 'Chocolate Fudge Celebration Cake',
                'description' => 'Decadent triple-layer chocolate cake with rich fudge frosting. Perfect for any celebration!',
                'price' => 38.00,
                'discount_price' => 34.99,
                'category' => 'Cakes & Celebration',
                'category_id' => 2,
                'stock_quantity' => 6,
                'sku' => 'CAKE-CF-001',
                'weight' => 1.50,
                'dimensions' => '22x22x12cm',
                'ingredients' => json_encode(['flour', 'cocoa', 'eggs', 'sugar', 'butter', 'chocolate']),
                'allergens' => json_encode(['gluten', 'dairy', 'eggs']),
                'status' => 'active',
                'rating' => 4.92,
                'rating_count' => 55,
                'is_featured' => false,
                'meta_title' => 'Triple Chocolate Fudge Cake',
                'meta_description' => 'Rich chocolate celebration cake',
                'image_path' => null,
                'images' => json_encode([]),
            ],

            // PASTRIES & CROISSANTS Category (Category 3)
            [
                'owner_id' => 2,
                'name' => 'Butter Croissant',
                'description' => 'Flaky, buttery French croissant with layers of crispy pastry. Perfect for breakfast.',
                'price' => 3.50,
                'discount_price' => null,
                'category' => 'Pastries & Croissants',
                'category_id' => 3,
                'stock_quantity' => 40,
                'sku' => 'PAST-CRO-001',
                'weight' => 0.08,
                'dimensions' => '15x10x8cm',
                'ingredients' => json_encode(['flour', 'butter', 'milk', 'sugar', 'yeast']),
                'allergens' => json_encode(['gluten', 'dairy']),
                'status' => 'active',
                'rating' => 4.85,
                'rating_count' => 142,
                'is_featured' => true,
                'meta_title' => 'Classic Butter Croissant',
                'meta_description' => 'Freshly baked French croissant',
                'image_path' => null,
                'images' => json_encode([]),
            ],
            [
                'owner_id' => 3,
                'name' => 'Pain au Chocolat',
                'description' => 'Classic French pastry with rich chocolate filling. A chocolate lover\'s dream!',
                'price' => 4.00,
                'discount_price' => 3.50,
                'category' => 'Pastries & Croissants',
                'category_id' => 3,
                'stock_quantity' => 35,
                'sku' => 'PAST-PAC-001',
                'weight' => 0.10,
                'dimensions' => '14x8x6cm',
                'ingredients' => json_encode(['flour', 'butter', 'chocolate', 'sugar', 'yeast']),
                'allergens' => json_encode(['gluten', 'dairy']),
                'status' => 'active',
                'rating' => 4.90,
                'rating_count' => 98,
                'is_featured' => true,
                'meta_title' => 'Pain au Chocolat',
                'meta_description' => 'French chocolate pastry',
                'image_path' => null,
                'images' => json_encode([]),
            ],
            [
                'owner_id' => 2,
                'name' => 'Almond Danish',
                'description' => 'Sweet Danish pastry filled with almond cream and topped with sliced almonds.',
                'price' => 4.25,
                'discount_price' => null,
                'category' => 'Pastries & Croissants',
                'category_id' => 3,
                'stock_quantity' => 30,
                'sku' => 'PAST-DAN-001',
                'weight' => 0.12,
                'dimensions' => '12x12x5cm',
                'ingredients' => json_encode(['flour', 'butter', 'almonds', 'sugar', 'eggs']),
                'allergens' => json_encode(['gluten', 'dairy', 'eggs', 'nuts']),
                'status' => 'active',
                'rating' => 4.75,
                'rating_count' => 64,
                'is_featured' => false,
                'meta_title' => 'Almond Danish Pastry',
                'meta_description' => 'Delicious almond-filled Danish',
                'image_path' => null,
                'images' => json_encode([]),
            ],

            // COOKIES & BISCUITS Category (Category 4)
            [
                'owner_id' => 2,
                'name' => 'Chocolate Chip Cookies (Box of 12)',
                'description' => 'Classic chocolate chip cookies with a crispy edge and chewy center. Made with premium chocolate chips.',
                'price' => 12.00,
                'discount_price' => 10.50,
                'category' => 'Cookies & Biscuits',
                'category_id' => 4,
                'stock_quantity' => 50,
                'sku' => 'COOKIE-CC-001',
                'weight' => 0.40,
                'dimensions' => '25x20x5cm',
                'ingredients' => json_encode(['flour', 'butter', 'sugar', 'eggs', 'chocolate chips', 'vanilla']),
                'allergens' => json_encode(['gluten', 'dairy', 'eggs']),
                'status' => 'active',
                'rating' => 4.90,
                'rating_count' => 156,
                'is_featured' => true,
                'meta_title' => 'Homemade Chocolate Chip Cookies',
                'meta_description' => 'Fresh baked chocolate chip cookies',
                'image_path' => null,
                'images' => json_encode([]),
            ],
            [
                'owner_id' => 3,
                'name' => 'Assorted Cookie Box (24 pieces)',
                'description' => 'Mixed box of our best cookies: chocolate chip, oatmeal raisin, sugar cookies, and double chocolate.',
                'price' => 22.00,
                'discount_price' => 19.99,
                'category' => 'Cookies & Biscuits',
                'category_id' => 4,
                'stock_quantity' => 25,
                'sku' => 'COOKIE-ASS-001',
                'weight' => 0.80,
                'dimensions' => '30x25x8cm',
                'ingredients' => json_encode(['flour', 'butter', 'sugar', 'eggs', 'chocolate', 'oats', 'raisins']),
                'allergens' => json_encode(['gluten', 'dairy', 'eggs']),
                'status' => 'active',
                'rating' => 4.88,
                'rating_count' => 73,
                'is_featured' => true,
                'meta_title' => 'Assorted Cookie Box',
                'meta_description' => 'Mixed cookie variety box',
                'image_path' => null,
                'images' => json_encode([]),
            ],
            [
                'owner_id' => 2,
                'name' => 'Oatmeal Raisin Cookies (Box of 12)',
                'description' => 'Chewy oatmeal cookies loaded with plump raisins. A healthier sweet treat!',
                'price' => 11.00,
                'discount_price' => null,
                'category' => 'Cookies & Biscuits',
                'category_id' => 4,
                'stock_quantity' => 45,
                'sku' => 'COOKIE-OR-001',
                'weight' => 0.38,
                'dimensions' => '25x20x5cm',
                'ingredients' => json_encode(['oats', 'flour', 'raisins', 'butter', 'sugar', 'eggs', 'cinnamon']),
                'allergens' => json_encode(['gluten', 'dairy', 'eggs']),
                'status' => 'active',
                'rating' => 4.60,
                'rating_count' => 45,
                'is_featured' => false,
                'meta_title' => 'Oatmeal Raisin Cookies',
                'meta_description' => 'Chewy oatmeal cookies with raisins',
                'image_path' => null,
                'images' => json_encode([]),
            ],

            // CUSTOM ORDERS Category (Category 5)
            [
                'owner_id' => 3,
                'name' => 'Custom Cupcakes (Box of 12)',
                'description' => 'Design your own cupcakes! Choose flavors, frosting colors, and decorations. Perfect for parties and events.',
                'price' => 36.00,
                'discount_price' => null,
                'category' => 'Custom Orders',
                'category_id' => 5,
                'stock_quantity' => 0,
                'sku' => 'CUST-CUP-001',
                'weight' => 1.00,
                'dimensions' => '30x25x10cm',
                'ingredients' => json_encode(['flour', 'sugar', 'eggs', 'butter', 'custom toppings']),
                'allergens' => json_encode(['gluten', 'dairy', 'eggs']),
                'status' => 'active',
                'rating' => 4.93,
                'rating_count' => 112,
                'is_featured' => true,
                'meta_title' => 'Custom Designed Cupcakes',
                'meta_description' => 'Personalized cupcakes for any occasion',
                'image_path' => null,
                'images' => json_encode([]),
            ],
            [
                'owner_id' => 2,
                'name' => 'Personalized Cookie Set (20 pieces)',
                'description' => 'Hand-decorated cookies with custom messages or designs. Great for corporate events, weddings, or parties.',
                'price' => 40.00,
                'discount_price' => null,
                'category' => 'Custom Orders',
                'category_id' => 5,
                'stock_quantity' => 0,
                'sku' => 'CUST-COOK-001',
                'weight' => 0.65,
                'dimensions' => '30x20x6cm',
                'ingredients' => json_encode(['flour', 'butter', 'sugar', 'eggs', 'royal icing', 'food coloring']),
                'allergens' => json_encode(['gluten', 'dairy', 'eggs']),
                'status' => 'active',
                'rating' => 4.96,
                'rating_count' => 84,
                'is_featured' => true,
                'meta_title' => 'Personalized Decorated Cookies',
                'meta_description' => 'Custom cookies for special occasions',
                'image_path' => null,
                'images' => json_encode([]),
            ],
            [
                'owner_id' => 3,
                'name' => 'Custom Macaron Tower (48 pieces)',
                'description' => 'Elegant macaron tower in your choice of colors and flavors. Perfect centerpiece for events.',
                'price' => 85.00,
                'discount_price' => null,
                'category' => 'Custom Orders',
                'category_id' => 5,
                'stock_quantity' => 0,
                'sku' => 'CUST-MAC-001',
                'weight' => 1.20,
                'dimensions' => '35x35x30cm',
                'ingredients' => json_encode(['almond flour', 'egg whites', 'sugar', 'buttercream', 'flavorings']),
                'allergens' => json_encode(['nuts', 'eggs', 'dairy']),
                'status' => 'active',
                'rating' => 5.00,
                'rating_count' => 41,
                'is_featured' => true,
                'meta_title' => 'Custom Macaron Tower',
                'meta_description' => 'Elegant macaron display for events',
                'image_path' => null,
                'images' => json_encode([]),
            ],

            // BAKERY BUNDLES Category (Category 6)
            [
                'owner_id' => 2,
                'name' => 'Breakfast Bundle',
                'description' => 'Start your day right! Includes 2 croissants, 1 loaf of bread, 4 muffins, and fresh orange juice.',
                'price' => 28.00,
                'discount_price' => 24.99,
                'category' => 'Bakery Bundles',
                'category_id' => 6,
                'stock_quantity' => 15,
                'sku' => 'BUNDLE-BF-001',
                'weight' => 1.80,
                'dimensions' => '35x25x15cm',
                'ingredients' => json_encode(['assorted breakfast items']),
                'allergens' => json_encode(['gluten', 'dairy', 'eggs']),
                'status' => 'active',
                'rating' => 4.82,
                'rating_count' => 67,
                'is_featured' => true,
                'meta_title' => 'Breakfast Bundle Box',
                'meta_description' => 'Complete breakfast package from local bakery',
                'image_path' => null,
                'images' => json_encode([]),
            ],
            [
                'owner_id' => 3,
                'name' => 'Party Celebration Box',
                'description' => 'Everything you need for a party! Includes 24 cupcakes, 2 dozen cookies, and party decorations.',
                'price' => 75.00,
                'discount_price' => 69.99,
                'category' => 'Bakery Bundles',
                'category_id' => 6,
                'stock_quantity' => 10,
                'sku' => 'BUNDLE-PAR-001',
                'weight' => 3.50,
                'dimensions' => '45x35x20cm',
                'ingredients' => json_encode(['assorted party treats']),
                'allergens' => json_encode(['gluten', 'dairy', 'eggs', 'nuts']),
                'status' => 'active',
                'rating' => 4.91,
                'rating_count' => 93,
                'is_featured' => true,
                'meta_title' => 'Party Celebration Bundle',
                'meta_description' => 'Complete party package with cupcakes and cookies',
                'image_path' => null,
                'images' => json_encode([]),
            ],
            [
                'owner_id' => 2,
                'name' => 'Artisan Gift Hamper',
                'description' => 'Luxury gift box with sourdough bread, artisan cookies, premium pastries, and gourmet coffee.',
                'price' => 55.00,
                'discount_price' => null,
                'category' => 'Bakery Bundles',
                'category_id' => 6,
                'stock_quantity' => 20,
                'sku' => 'BUNDLE-GIFT-001',
                'weight' => 2.50,
                'dimensions' => '40x30x15cm',
                'ingredients' => json_encode(['premium bakery items']),
                'allergens' => json_encode(['gluten', 'dairy', 'nuts']),
                'status' => 'active',
                'rating' => 4.88,
                'rating_count' => 58,
                'is_featured' => true,
                'meta_title' => 'Artisan Bakery Gift Hamper',
                'meta_description' => 'Premium bakery gift box',
                'image_path' => null,
                'images' => json_encode([]),
            ],
            [
                'owner_id' => 3,
                'name' => 'Corporate Catering Box',
                'description' => 'Perfect for office meetings! 12 assorted pastries, 12 cookies, and disposable serving items.',
                'price' => 48.00,
                'discount_price' => 44.99,
                'category' => 'Bakery Bundles',
                'category_id' => 6,
                'stock_quantity' => 12,
                'sku' => 'BUNDLE-CORP-001',
                'weight' => 2.20,
                'dimensions' => '40x30x12cm',
                'ingredients' => json_encode(['assorted office treats']),
                'allergens' => json_encode(['gluten', 'dairy', 'eggs', 'nuts']),
                'status' => 'active',
                'rating' => 4.85,
                'rating_count' => 76,
                'is_featured' => false,
                'meta_title' => 'Corporate Catering Box',
                'meta_description' => 'Office meeting catering package',
                'image_path' => null,
                'images' => json_encode([]),
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(
                ['sku' => $product['sku']],
                $product
            );
        }
    }
}

